Example.1

In [1]:
import numpy as np
a = np.array([1,3,4]) 
b = np.array([2,7,-5])
ans = np.cross(a,b)
print(ans)

[-43  13   1]


Example.2

In [2]:
from sympy import *
a1,a2,a3 = symbols("a1 a2 a3")
a = np.array([a1,a2,a3])
ans = np.cross(a,a)
print(ans)

[0 0 0]


Example.3

In [3]:
P = np.array([1,4,6]) 
Q = np.array([-2,5,-1])
R = np.array([1,-1,1])
PQ = Q - P
PR = R - P
ans = np.cross(PQ,PR)
print(ans)

[-40 -15  15]


Example.4

In [4]:
P = np.array([1,4,6]) 
Q = np.array([-2,5,-1])
R = np.array([1,-1,1])
PQ = Q - P
PR = R - P
cross_product = np.cross(PQ,PR)
norm_cross = np.linalg.norm(cross_product)
area = 0.5*norm_cross
print(area)

22.6384628453


Example.5

In [5]:
a = np.array([1,4,-7]) 
b = np.array([2,-1,4])
c = np.array([0,-9,18])
triple_product = a.dot(np.cross(b,c))
print(triple_product)

0


Example.6

In [6]:
r = 0.25
F = 40
theta = 75/180*np.pi
torque = r*F*np.sin(theta)
print(torque)

9.65925826289
