Example3

In [1]:
import numpy as np
A = np.array([2,-3,4])
B = np.array([-2,1,1])
print(B-A)


[-4  4 -3]


Example4

In [2]:
A = np.array([4,0,3])
B = np.array([-2,1,5])
print(A + B)
print(A - B)
print(3*B)
print(2*A + 5*B)

[2 1 8]
[ 6 -1 -2]
[-6  3 15]
[-2  5 31]


Example6

In [3]:
from numpy import linalg as LA
A = np.array([2,-1,-2])
unit_vector = A/LA.norm(A)
print(unit_vector)

[ 0.66666667 -0.33333333 -0.66666667]


Example7

In [4]:
theta1 = 50.0/180*np.pi
theta2 = 32.0/180*np.pi
a = np.array([[-np.cos(theta1),np.cos(theta2)], [np.sin(theta1),np.sin(theta2)]])
b = np.array([0,100])
x = np.linalg.solve(a, b)
print(x)

[ 85.63823503  64.91046515]
